-- MIIS Database Schema (Pages 18-20 of Architectural Document)

CREATE TABLE IF NOT EXISTS miis_incidents (
  incident_id TEXT PRIMARY KEY,
  event_date TEXT,
  event_date_precision TEXT,
  report_date TEXT,
  country TEXT DEFAULT 'Sri Lanka',
  province TEXT,
  district TEXT,
  ds_division TEXT,
  nearest_town TEXT,
  location_name TEXT,
  original_location_text TEXT,
  site_type TEXT,
  latitude REAL,
  longitude REAL,
  spatial_precision TEXT,
  coordinate_confidence TEXT,
  coordinate_source TEXT,
  gps_accuracy_m REAL,
  uncertainty_radius_km REAL,
  distance_to_coast_km REAL,
  location_validation_status TEXT,
  event_type TEXT,
  taxon_group TEXT,
  species_common TEXT,
  species_scientific TEXT,
  condition_status TEXT,
  number_dead INTEGER,
  number_alive INTEGER,
  quantity_text TEXT,
  number_precision TEXT,
  cause_category TEXT,
  suspected_cause TEXT,
  cause_certainty TEXT,
  urgency_level TEXT,
  response_status TEXT,
  confidence_score NUMERIC,
  confidence_class TEXT,
  validation_level TEXT,
  validation_status TEXT,
  duplicate_group_id TEXT,
  public_visibility TEXT,
  sensitive_location BOOLEAN DEFAULT 0,
  notes TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS miis_citizen_reports (
  report_id TEXT PRIMARY KEY,
  user_id TEXT,
  submitted_at TEXT,
  observed_at TEXT,
  event_type TEXT,
  taxon_group TEXT,
  species_guess TEXT,
  condition_status TEXT,
  quantity_range TEXT,
  number_observed INTEGER,
  latitude REAL,
  longitude REAL,
  gps_accuracy_m REAL,
  location_name TEXT,
  photo_urls TEXT,
  video_urls TEXT,
  notes TEXT,
  pollution_oil BOOLEAN DEFAULT 0,
  pollution_plastic BOOLEAN DEFAULT 0,
  pollution_nurdles BOOLEAN DEFAULT 0,
  pollution_net BOOLEAN DEFAULT 0,
  pollution_chemical_smell BOOLEAN DEFAULT 0,
  injury_visible BOOLEAN DEFAULT 0,
  ai_taxon_prediction TEXT,
  ai_event_prediction TEXT,
  ai_confidence NUMERIC,
  duplicate_risk NUMERIC,
  review_status TEXT,
  expert_validation_status TEXT,
  final_incident_id TEXT,
  points_awarded INTEGER DEFAULT 0,
  safety_warning_shown BOOLEAN DEFAULT 1,
  public_visibility TEXT DEFAULT 'public'
);

CREATE TABLE IF NOT EXISTS miis_sources (
  source_id TEXT PRIMARY KEY,
  incident_id TEXT,
  source_type TEXT,
  source_name TEXT,
  source_url TEXT,
  archive_url TEXT,
  title TEXT,
  author TEXT,
  publication_date TEXT,
  collection_date TEXT DEFAULT CURRENT_TIMESTAMP,
  language TEXT DEFAULT 'en',
  raw_text_path TEXT,
  media_path TEXT,
  credibility_score INTEGER,
  evidence_sentence TEXT,
  source_confidence TEXT
);

CREATE TABLE IF NOT EXISTS miis_rewards (
  reward_id TEXT PRIMARY KEY,
  user_id TEXT,
  report_id TEXT,
  reward_type TEXT,
  points INTEGER,
  badge_name TEXT,
  reason TEXT,
  awarded_at TEXT DEFAULT CURRENT_TIMESTAMP
);
